services:
  - name: webtop
    type: web
    envVars:
      - key: PUID
        value: "1000"
      - key: PGID
        value: "1000"
      - key: TZ
        value: "Etc/UTC"
      - key: SUBFOLDER
        value: "/" # optional
      - key: TITLE
        value: "Webtop" # optional
    volumes:
      - "/home/user/data:/config"
      - "/var/run/docker.sock:/var/run/docker.sock" # optional
    ports:
      - "3000:3000"
      - "3001:3001"
    devices:
      - "/dev/dri:/dev/dri" # optional
    shmSize: "1gb" # optional
    healthCheckPath: "/" # optional
    skipClean: false # optional
    disk: "256" # optional
    plan: "free" # optional
    repo: # optional
    region: "us-east-1" # optional
    restartPolicy:
      unless-stopped
